#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
#
#  Copyright 2017 Daniel Cruz <bwb0de@bwb0dePC>
#  Version 0.1
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#
#


"""

Programa para gestão do combate

Usage:
    formmaker add
    formmaker run

Options:
    --version

"""

import os

from docopt import docopt

from modules.cli_tools import select_op, azul_claro
from modules.py_obj_data_tools import Form
from modules.py_pickle_handlers import load_selected_pickle_ob

pasta_formularios = os.getcwd() + os.sep + 'data/'

args = docopt(__doc__)

def main():
    if args['add']:
        Form("Formulário", pasta_formularios)

    elif args['run']:
        form_selected = next(load_selected_pickle_ob('Selecione o formulário a ser preenchido:', pasta_formularios))
        print(form_selected.executar_formulario())




if __name__ == '__main__':
	main()
